Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
